/**
 * キーワードのルールでは決まらなかった語を、1語ずつ置いた表。
 * scripts/lib/themeRules.js のルールより先に見る（見出しの完全一致）。
 *
 * ここに並ぶのは「意味は分かるが、他の語と共通の手がかりが無い」語。
 * 語彙が増えたら scripts/assignThemes.js --rest で炙り出して足す。
 */

const THEME_OVERRIDES = {
  seeing: [
    "glare at",
    "gleam",
    "horizon",
    "illustration",
    "portrait",
    "print",
    "visibility",
    "icon",
    "poster",
    "symbol",
    "token",
    "mark",
    "mark out ～",
    "frisk",
    'blur', 'detection', 'disguise', 'exhibition', 'flicker', 'discern', 'expose',
  ],
  speaking: [
    "get at",
    "get in touch with",
    "glossary",
    "hint",
    "homage",
    "I beg your pardon?",
    "idiom",
    "in a nutshell",
    "inquire",
    "interview",
    "interviewer",
    "joke",
    "joking/kidding aside",
    "journalism",
    "maxim",
    "metaphor",
    "monologue",
    "murmur",
    "mutter",
    "My pleasure.",
    "note",
    "preface",
    "pronoun",
    "prophecy",
    "prophet",
    "prose",
    "proverb",
    "publication",
    "questionnaire",
    "recite",
    "reference",
    "reporter",
    "respondent",
    "rhetoric",
    "saying",
    "sermon",
    "slang",
    "speaking/talking of ～",
    "specify",
    "spell",
    "stand for ～",
    "testimony",
    "That is that",
    "That's it",
    "to put it … / put …",
    "topic",
    "tweet",
    "verb",
    "vow",
    "What about ~?",
    "What's the matter?",
    "Why don't we ...?",
    "You are welcome",
    "You're kidding (me).",
    "Let's ~.",
    "let's",
    "How about...?",
    "keep in touch",
    "put emphasis/stress on/upon ～",
    "play up ～",
    "riddle",
    "Legend has it (that) …",
    "legend",
    "no sooner ～ than …",
    'advice', 'appeal', 'blog', 'communication', 'compliment', 'confide in',
    'correspondence', 'correspondent', 'dialect', 'dialogue', 'divulge', 'edit',
    'edition', 'editor', 'eloquence', 'email', 'encyclopedia', 'epilogue', 'episode',
    'eulogy', 'excerpt', 'expound', 'and so on/forth', 'Can you...?', 'Could you...?',
  ],
  listening: [
    "guitar",
    "musical",
    "piano",
    "pianist",
    "pop",
    "radio",
    "TV",
    "television",
    "video",
    "videogame",
    "tune",
    "tune up (～)",
    "violin",
    "website",
    "media",
    "masterpiece",
    "Renaissance",
    "tune in (to ～)",
    'album', 'anime', 'concert', 'chorus', 'drum', 'flute', 'echo', 'fluency',
  ],
  thinking: [
    "It is ～ for ... to do",
    "It is ～ that SV",
    "I prefer ～",
    "so ～ that ...",
    "have both advantages and disadvantages",
    "To give an example, ～",
    "In addition, ～",
    "Moreover, ～",
    "Besides, ～",
    "In contrast, ～",
    "Thus, ～",
    "In summary, ～",
    "be related to privacy",
    "for instance",
    "forgo",
    "generalization",
    "generalize",
    "have ～ to do with",
    "have nothing to do with",
    "have something to do with",
    "hinge on",
    "hunch",
    "if only",
    "ignorance",
    "ignorant of/about",
    "illusion",
    "imitation",
    "impression",
    "in a bind",
    "in a jam",
    "in accord with",
    "in accordance with",
    "in advance",
    "in any case",
    "in compliance with",
    "in connection with",
    "in contrast to/with",
    "in favor of",
    "in general",
    "in line with",
    "in order to",
    "in pursuit of",
    "in retrospect",
    "in search of",
    "in the event of ～",
    "intelligence",
    "It is no use doing",
    "justify",
    "know",
    "might (just) as well do",
    "narrow down ～",
    "no longer ～",
    "none other than ～",
    "not ... at all",
    "not at all",
    "nothing but ～",
    "of one's (own) doing",
    "of one's own accord/free will",
    "of one's own",
    "on ～ terms with …",
    "only too",
    "priority",
    "prospect",
    "quest",
    "regard A as B",
    "regardless of ～",
    "relate",
    "relationship",
    "retrospect",
    "revise",
    "search for ～",
    "search for",
    "search",
    "seek",
    "self",
    "sense",
    "so ～ that …",
    "so that ～ can do",
    "something of a ～",
    "sort out ～",
    "stance",
    "such as it is",
    "such as",
    "superstition",
    "the former A, the latter B",
    "the key to",
    "up to ～",
    "up to",
    "want for ～",
    "what with A and B",
    "whim",
    "with all ～",
    "would/had rather do (than ～)",
    "wit",
    "meditate",
    "meditation",
    "motive",
    "opportunity",
    "permission",
    "permit",
    "pretend",
    "process",
    "refusal",
    "refuse",
    "reject",
    "secret",
    "situation",
    "type",
    "up to date",
    "this and that",
    "from A to B",
    "get by",
    "get down to",
    "get ahead",
    'A is to B what C is to D', 'according to', 'analogy', 'apply', 'approve',
    'agree with', 'ascribe A to B', 'as opposed to', 'apart from', 'aside from',
    'both ... and', 'by all means', 'by choice', 'by the way', 'cannot but do',
    'cannot help doing', 'category', 'classify', 'comprise', 'consist of', 'consist',
    'construe A as B', 'construe', 'contrary to', 'conviction', 'deserve',
    'differentiate', 'discrepancy', 'disapproval', 'disapprove of', 'dissent',
    'distinguish', 'distrust', 'downplay', 'each and every', 'either A or B',
    'equate A with B', 'err', 'error', 'essential for/to', 'even though',
    'every other', 'exception', 'exclude A from B', 'exclude', 'exclusion',
    'exemplify', 'familiar with', 'find fault with', 'for example', 'all too',
    'as ... as', 'as well', 'at best', 'dare to do', 'determination', 'dichotomy',
    'dilemma', 'domain', 'emphasis', 'emphasize', 'endorse', 'espouse', 'favor',
    'focus', 'conceal A from B', 'conceal', 'cover up', 'compliance', 'adhere to',
    'abstain from',
  ],
  emotion: [
    "I want to ～",
    "It helps me relax",
    "frenzy",
    "friendly with",
    "frown on/upon",
    "frown",
    "frustrate",
    "grudge",
    "groan",
    "hail",
    "horrify",
    "hostility",
    "hug",
    "humor",
    "hysteria",
    "idol",
    "in favor with",
    "in honor of",
    "luck",
    "malice",
    "melancholy",
    "mercy",
    "mourn",
    "hardship",
    "relax",
    "revenge",
    "scold",
    "self-esteem",
    "thrill",
    "trouble",
    "upset",
    "uproar",
    "vanity",
    "vigor",
    "worship",
    "yearn for ～",
    "yearn",
    "welcome",
    "misfortune",
    "freak",
    'absorb', 'charm', 'covet', 'crave', 'curse', 'deplore', 'despise', 'detest',
    'dismay', 'distress', 'embarrassment', 'engrossed in', 'entice', 'envy',
    'fascinate', 'fascination', 'favorite', 'flinch', 'flirt', 'dream', 'disgrace',
    'at one\'s ease', 'clamor',
  ],
  movement: [
    "stand",
    "lay",
    "keep off ～",
    "in a hurry",
    "get off",
    "hurtle",
    "hurry up",
    "hurry",
    "influx",
    "lift off",
    "on board (～)",
    "parade",
    "pedestrian",
    "precede",
    "procession",
    "raid",
    "recede",
    "relay",
    "retreat",
    "roll up ～",
    "runner",
    "set off ～",
    "skate",
    "ski",
    "skiing",
    "skip",
    "sneak",
    "stay",
    "step",
    "stride",
    "stroll",
    "taxi",
    "track",
    "wander off",
    "wait for",
    "wait",
    "up and down",
    "sit by",
    "sit down",
    "sit in",
    "sit",
    "sweep",
    "steer",
    "out of",
    "partake",
    "participate in ～",
    "participate",
    "participation",
    "throng",
    "rally",
    'accompany', 'ahead of', 'await', 'bound for', 'bump into', 'bump', 'circle',
    'circulate', 'close in on', 'crawl', 'cruise', 'descend', 'descent', 'disembark',
    'dispatch', 'displace', 'divert', 'dodge', 'drop off', 'drop', 'escort', 'evade',
    'expedition', 'exploration', 'ferry', 'flock to', 'by way of', 'circumvent',
    'deviate from', 'flounder', 'doze off',
  ],
  making: [
    "bullet",
    "cover",
    "handicap",
    "link",
    "pilot",
    "poison",
    "rose",
    "separate",
    "souvenir",
    "thing",
    "Internet",
    "framework",
    "funnel",
    "furnace",
    "furnish A with B",
    "furnish",
    "greenhouse",
    "grind",
    "guidebook",
    "hack",
    "hang",
    "hole",
    "hook up",
    "implant",
    "ink",
    "install",
    "iron",
    "jar",
    "kite",
    "knit",
    "knock",
    "label",
    "lamp",
    "landfill",
    "lid",
    "needle",
    "net",
    "network",
    "object",
    "original",
    "ornament",
    "pave",
    "PC",
    "pillar",
    "pit",
    "platform",
    "pocket",
    "pole",
    "pottery",
    "program",
    "programmer",
    "puzzle",
    "racket",
    "rag",
    "reconstruct",
    "recycle",
    "refrigerator",
    "renovate",
    "replicate",
    "reproduce",
    "robot",
    "rocket",
    "rope",
    "rubber",
    "scissors",
    "scoop up ～",
    "scrape",
    "seal",
    "seesaw",
    "shape",
    "smartphone",
    "sofa",
    "spray",
    "stapler",
    "stationery",
    "statue",
    "stick",
    "storage",
    "stretch",
    "string",
    "stuff",
    "style",
    "suitcase",
    "table",
    "tablet",
    "tailor",
    "tent",
    "tower",
    "toy",
    "trim",
    "T-shirt",
    "umbrella",
    "use up ～",
    "use",
    "user",
    "VCR",
    "warehouse",
    "weapon",
    "wipe",
    "wrap up ～",
    "yacht",
    "sword",
    "smash",
    "streamline",
    "synthesis",
    "synthesize",
    "tighten",
    "tie",
    "shirt",
    "skirt",
    "scarf",
    "sweater",
    "pants",
    "medal",
    "mall",
    "table tennis",
    "fringe",
    "funeral",
    'apron', 'backpack', 'belt', 'block', 'broil', 'buckle up', 'bury', 'compile',
    'compress', 'condense', 'complete', 'copy', 'decorate', 'dilate', 'dilute',
    'distill', 'doll', 'dress', 'dress up', 'drone', 'duplicate', 'dye', 'dry',
    'embed', 'equip', 'extract A from B', 'extract', 'fasten', 'fill up', 'flag',
    'fluid', 'accomplish', 'cast', 'clutter', 'diamond', 'flake', 'ditch',
  ],
  place: [
    "geography",
    "homeland",
    "homeroom",
    "hometown",
    "London",
    "longitude",
    "Kenya",
    "Peru",
    "Singapore",
    "Thailand",
    "prefecture",
    "prison",
    "jail",
    "pond",
    "pool",
    "slope",
    "terminal",
    "tomb",
    "top",
    "waterfall",
    "world",
    "World Heritage Site",
    "hemisphere",
    "galaxy",
    "grave",
    "middle",
    "suite",
    "supermarket",
    "row",
    "toilet",
    "lawn",
    "homestay",
    "picnic",
    "line",
    'address', 'altitude', 'bathroom', 'cafeteria', 'center', 'closure', 'dorm',
    'downtown', 'entry', 'close down', 'bottom', 'core', 'camp', 'camping',
  ],
  time: [
    "on weekends",
    "for life",
    "hold on",
    "hold up ～",
    "meantime",
    "millennium",
    "semester",
    "these days",
    "Halloween",
    "reschedule",
    "standby",
    "preparation",
    "hold out",
    'birthday', 'by degrees', 'calendar', 'date', 'ceremony', 'die down',
  ],
  quantity: [
    "gram",
    "hundreds of",
    "kilogram",
    "kilometer",
    "lump",
    "meter",
    "multitude",
    "pair",
    "piece",
    "quota",
    "ration",
    "round",
    "score",
    "speed",
    "step up ～",
    "temperature",
    "velocity",
    'a handful of', 'a variety of', 'deficiency', 'deficit', 'equation',
    'equilibrium', 'copy of', 'excellence',
  ],
  work: [
    "for free",
    "franchise",
    "freight",
    "gamble",
    "gift",
    "give out",
    "gold",
    "incentive",
    "inflation",
    "initiative",
    "lawyer",
    "mark down ～",
    "merchant",
    "merit",
    "monopoly",
    "offer",
    "patent",
    "penalty",
    "poverty",
    "privilege",
    "quit",
    "refund",
    "regulation",
    "repay",
    "representative",
    "reservation",
    "reserve",
    "revenue",
    "robbery",
    "sanction",
    "savings",
    "secretary",
    "servant",
    "silver",
    "sponsor",
    "subsidize",
    "subsidy",
    "successor",
    "supervise",
    "support",
    "theft",
    "ticket",
    "union",
    "warrant",
    "yen",
    "stake",
    "roll out ～",
    "prescription",
    'allocate', 'assign', 'at ～\'s disposal', 'bribe', 'coin', 'collateral',
    'contractor', 'consumption', 'corrupt', 'coupon', 'credentials', 'default',
    'delegate', 'demand', 'deposit', 'depreciation', 'designer', 'dollar', 'donor',
    'embezzle', 'employee', 'engineer', 'endow', 'entrust A with B', 'exempt from',
    'exposition', 'commit A to B', 'commit oneself to', 'commit', 'compete',
    'engage in', 'dedication', 'devotion', 'compromise', 'confer A on B',
  ],
  people: [
    "be required to do",
    "be popular among ～",
    "be independent",
    "grandchild",
    "impunity",
    "invasion",
    "legacy",
    "ransom",
    "revolt",
    "sacrifice",
    "volunteer",
    "disparage",
    "descendant",
    "English",
    "estrangement",
    "extrovert",
    "fiat",
    "forbid A to do",
    "forbid",
    "forerunner",
    "foster",
    "fray",
    "freshman",
    "friction",
    "fugitive",
    "heir",
    "heritage",
    "hermit",
    "heroine",
    "homicide",
    "hostage",
    "idiot",
    "impersonate",
    "implicate",
    "in the presence of ～",
    "in private",
    "in secret",
    "infant",
    "inhabit",
    "inherit",
    "isolate",
    "isolation",
    "jury",
    "kin",
    "layman",
    "liberate",
    "liberty",
    "lifestyle",
    "living",
    "Muslim",
    "murder",
    "offspring",
    "officer",
    "on [in] behalf of A",
    "on behalf of",
    "outsider",
    "partner",
    "passport",
    "peasant",
    "persecute",
    "persecution",
    "pilgrim",
    "prisoner",
    "Protestant",
    "proponent",
    "posterity",
    "punish A for B",
    "rebel",
    "regime",
    "republic",
    "reunion",
    "riot",
    "rival",
    "saint",
    "scandal",
    "sibling",
    "sin",
    "slaughter",
    "snob",
    "socialize",
    "sophomore",
    "spouse",
    "superpower",
    "surrender to ～",
    "terrorism",
    "toddler",
    "triplet",
    "tyranny",
    "uncle",
    "unify",
    "unity",
    "United Nations",
    "victim",
    "warrior",
    "salute",
    "summon",
    "stand by ～",
    "stand up to ～",
    "single out ～",
    "brass band",
    "Senate",
    'adolescent', 'assault', 'aunt', 'autonomy', 'co-author', 'coexist',
    'cohabitation', 'compel A to do', 'conspiracy', 'constitution', 'convene',
    'convoy', 'coup', 'cripple', 'crew', 'culprit', 'cult', 'custody', 'dictator',
    'dignitary', 'dignity', 'disarm', 'dissident', 'divorce', 'elder', 'elite',
    'emancipate', 'emergency', 'enact', 'enemy', 'envoy', 'errand', 'fanatic',
    'feud', 'fight', 'fleet', 'flagship', 'foe', 'fool', 'confront', 'contend with',
    'detain', 'each other', 'empire', 'connection', 'connect', 'conjunction',
    'clamp down on', 'congestion',
  ],
  learning: [
    "geometry",
    "globalization",
    "golf",
    "jogging",
    "join",
    "major in ～",
    "major",
    "modernization",
    "innovation",
    "genesis",
    "genre",
    "recommend",
    "rugby",
    "subject",
    "diligence",
    'AI', 'archaeology', 'beginner', 'classmate', 'club', 'drop out of', 'enlighten',
    'enlightenment', 'enroll', 'etymology', 'excel in/at', 'experience', 'feat',
    'check in', 'cortex', 'embryo', 'enigma', 'edition of',
  ],
  body: [
    "grip",
    "touch",
    "survival",
    "pet",
    "hormone",
    "inhale",
    "injection",
    "jaw",
    "joint",
    "obesity",
    "paralyze",
    "protein",
    "pulse",
    "sprain",
    "strangle",
    "stun",
    "swell",
    "syndrome",
    "tumor",
    "vein",
    "vet",
    "veterinarian",
    "vitamin",
    "vomit",
    "wrinkle",
    "throw up (～)",
    "surgeon",
    "sensation",
    "stink",
    "fragrance",
    "hide-and-seek",
    'death', 'devour', 'fishing',
  ],
  nature: [
    "frost",
    "fume",
    "giraffe",
    "haze",
    "herb",
    "horde",
    "hurricane",
    "irrigation",
    "koala",
    "mosquito",
    "octopus",
    "owl",
    "oxygen",
    "ozone",
    "pine",
    "prey",
    "radiation",
    "rainbow",
    "rot",
    "rust",
    "smoke",
    "wheat",
    "wing",
    "wither",
    "cultivate",
    "hunt",
    "gravity",
    'bait', 'crane', 'dinosaur', 'dolphin', 'domesticate', 'erosion', 'evaporate',
    'famine', 'fodder', 'corrosion', 'dwarf', 'flourish',
  ],
  food: [
    "ham",
    "hamburger",
    "jam",
    "lettuce",
    "pie",
    "pineapple",
    "pizza",
    "popcorn",
    "pudding",
    "pumpkin",
    "spaghetti",
    "steak",
    "yogurt",
    "seafood",
    "petrol",
    'cucumber', 'curry', 'cookie',
  ],
  change: [
    "have difficulty ～ing",
    "struggle to do",
    "grapple with",
    "hold up",
    "eliminate A from B",
    "embody",
    "enclose",
    "encounter",
    "give off",
    "give up",
    "hasten",
    "hide",
    "hit",
    "hoard",
    "immerse",
    "impose A on B",
    "impress A with B",
    "incorporate",
    "indulge in ～",
    "inspire",
    "involve",
    "involvement",
    "kick",
    "kill",
    "leak",
    "lean",
    "lend",
    "let ～ in",
    "let down ～",
    "let",
    "lock in ～",
    "lower",
    "lure",
    "manipulate",
    "meet with ～",
    "meet",
    "mingle",
    "miss out on ～",
    "modify",
    "momentum",
    "navigate",
    "nod",
    "open",
    "outburst",
    "overdo",
    "overthrow",
    "overwork",
    "penetrate",
    "persist in ～",
    "pick",
    "play down ～",
    "play out (～)",
    "prefer A to B",
    "prefer",
    "proliferate",
    "prolong",
    "prosperity",
    "provide for ～",
    "pursue",
    "put aside ～",
    "put",
    "raise",
    "rattle",
    "refrain from ～",
    "refrain",
    "reform",
    "remain",
    "rest",
    "restrain",
    "ruin",
    "set ～ free",
    "set about ～",
    "set aside ～",
    "setback",
    "shake up ～",
    "shake",
    "shoot",
    "shower",
    "shut up ～",
    "shut",
    "smuggle",
    "spill",
    "spur",
    "stick to [by] ～",
    "stick to ～",
    "sustain",
    "tackle",
    "thrive",
    "transcend",
    "turmoil",
    "undermine",
    "unleash",
    "update",
    "uphold",
    "vanish",
    "was",
    "is",
    "ring",
    "round off ～",
    "soak",
    "tap",
    "give birth to",
    "strength",
    'bend', 'blow', 'close', 'defy', 'degrade', 'deter', 'disseminate', 'dissipate',
    'disturb', 'divergence', 'do without', 'do', 'download', 'emit', 'entail',
    'entangle', 'escalate', 'exist', 'expedite', 'extend', 'facilitate', 'destiny',
    'doom', 'fate', 'discharge', 'dispel', 'dispense with', 'deviation', 'curb',
    'extort', 'extenuate', 'catch', 'beat', 'belong to', 'belong', 'borrow',
    'bombard A with B', 'am', 'are', 'be',
  ],
  quality: [
    "beneficial",
    "innovative",
    "be beneficial to ～",
    "in spite of",
    "verge",
    "free from",
    "in flames",
    "in the way (of ～)",
    "in the way of A / in A's way",
    "in vain",
    "inability",
    "luxury",
    "magic",
    "harm",
    "hardly ever",
    "have difficulty in doing",
    "have no choice but to do",
    "hybrid",
    "liquid",
    "litter",
    "nuisance",
    "on (one's) guard",
    "on the brink of",
    "on the verge of ～",
    "on the verge of",
    "out of character",
    "out of order",
    "pressure",
    "proximity",
    "red",
    "to one's advantage",
    "to one's feet",
    "to oneself",
    "treasure",
    "trifle",
    "upbringing",
    "upward(s) of ～",
    "virtue",
    "with ease",
    "upside down",
    "stress",
    "mail",
    "post",
    "postcard",
    '(be) free of', '(in) the way', '(Just) As ..., so', 'at the expense of',
    'at the mercy of', 'at will', 'be famous for', 'be filled with', 'be ready to',
    'crowded with', 'devoid of', 'ease', 'elegance', 'exposure', 'fluke', 'foible',
    'advantage', 'activity', 'chance', 'by oneself', 'contingent on/upon',
    'contingent on', 'depend on', 'cling to', 'constraint',
  ],
};

/** 見出し → テーマ。同じ見出しが2度出てきたら気づけるようにする。 */
const WORD_TO_THEME = new Map();
for (const [theme, words] of Object.entries(THEME_OVERRIDES)) {
  for (const word of words) {
    if (WORD_TO_THEME.has(word) && WORD_TO_THEME.get(word) !== theme) {
      throw new Error(`themeOverrides: ${word} が ${WORD_TO_THEME.get(word)} と ${theme} の両方にあります`);
    }
    WORD_TO_THEME.set(word, theme);
  }
}

module.exports = { THEME_OVERRIDES, WORD_TO_THEME };
