/**
 * 英検ライティングの重要フレーズ。
 *
 * 出どころは先生から渡された「◯級合格ライティング道場」（3級 / 準2級 / 2級）。
 * 過去問から拾われた、書くときにそのまま使えるフレーズ。単語カードとは
 * 性格が違う（読んで意味が分かる語ではなく、書くために手が覚える型）ので、
 * 例文まで含めて1件にしてある。
 *
 * grade は英検の級。level（1〜7）へはスクリプト側で写す。
 * 見出しの伏せ字は ～ に統一する（マスターの既存の熟語と揃える）。
 */

/** [見出し, 意味, 例文, 例文の訳] */
const G3 = [
  // どのテーマにも使える型
  ['make A B', 'AをBにする', 'Exercise makes our bodies stronger.', '運動は私たちの体を強くする。'],
  ['be good for ～', '〜に良い', 'Walking for 30 minutes a day is good for your health.', '1日30分のウォーキングは体に良い。'],
  ['be bad for ～', '〜に悪い', 'Eating too much sugar is bad for your teeth.', '砂糖の取りすぎは歯に悪い。'],
  ['It is ～ for ... to do', '…が〜するのは〜だ', 'It is important for students to study English.', '生徒にとって英語を勉強することは重要だ。'],
  ['It is ～ that SV', '…することは〜だ', 'It is important that students study English.', '生徒が英語を勉強することは重要だ。'],
  ['can V easily', '簡単に〜できる', 'If you live near the station, you can commute to work easily.', '駅の近くに住めば、簡単に通勤することができます。'],
  ['If SV, SV', 'もし〜ならば…', "If it is sunny tomorrow, let's go outside.", '明日もし晴れたら、外出しましょう。'],
  ['I enjoy ～ing', '〜を楽しむ', 'I enjoy reading books.', '本を読むのを楽しみます。'],
  ['I want to ～', '〜したい', 'I want to play the videogame.', 'そのゲームをプレイしたいです。'],
  ['would like to ～', '〜したい', 'I would like to visit Kyoto someday.', 'いつか京都を訪れたいです。'],
  ['I feel happy when ～', '〜するとき幸せを感じる', 'I feel happy when I spend time with my friends.', '友達と過ごすとき幸せを感じます。'],
  ['～ is good for my health', '〜は健康に良い', 'Walking every day is good for my health.', '毎日歩くことは健康に良いです。'],
  ['I want to learn more about ～', '〜についてもっと学びたい', 'I want to learn more about other cultures.', 'ほかの文化についてもっと学びたいです。'],
  ['in my free time', '自由時間に', 'I often watch movies in my free time.', '自由時間によく映画を見ます。'],
  ['I am interested in ～', '〜に興味がある', 'I am interested in learning languages.', '言語を学ぶことに興味があります。'],
  ['It is boring', 'それは退屈だ', "I don't like doing homework because it is boring.", '宿題をするのは退屈なので好きではありません。'],
  ['It takes a lot of time', 'それは時間がかかる', "I don't want to cook dinner because it takes a lot of time.", '夕食を作りたくありません。時間がかかるからです。'],
  ['I prefer ～', '〜のほうを好む', 'I prefer staying home because it is more comfortable.', '家にいるほうが快適なので好みます。'],
  ['It costs a lot of money to ～', '〜するにはお金がかかる', 'It costs a lot of money to travel abroad.', '海外旅行にはたくさんお金がかかります。'],
  ['make good memories', '良い思い出を作る', 'I can make good memories by traveling with my family.', '家族と旅行することで良い思い出を作ることができます。'],
  // 形容詞（It is ～ to do と組み合わせる）
  ['comfortable', '快適な', 'It is comfortable to stay at home on rainy days.', '雨の日に家にいるのは快適です。'],
  ['healthy', '健康に良い', 'It is healthy to eat vegetables every day.', '毎日野菜を食べるのは健康に良いです。'],
  ['exciting', 'わくわくする', 'It is exciting to visit a new country.', '新しい国を訪れるのはワクワクします。'],
  ['enjoyable', '楽しめる', 'It is enjoyable to go shopping with friends.', '友達と買い物に行くのは楽しいです。'],
  // 将来
  ['I want to be ～ in the future', '将来〜になりたい', 'I want to be a doctor in the future.', '将来、医者になりたいです。'],
  ['I hope to ～ someday', 'いつか〜したい', 'I hope to work in another country someday.', 'いつか外国で働きたいです。'],
  ['follow my dream', '夢を追う', 'It is important to follow my dream and never give up.', '夢を追い、あきらめないことが大切です。'],
  ['make my dream come true', '夢を叶える', 'I want to study hard to make my dream come true.', '夢を叶えるために一生懸命勉強したいです。'],
  // 海外・文化
  ['learn about different cultures', 'さまざまな文化について学ぶ', 'I want to learn about different cultures by traveling.', '旅行を通してさまざまな文化について学びたいです。'],
  ['see famous places', '有名な場所を見る', 'It is exciting to see famous places.', '有名な場所を見るのはワクワクします。'],
  // 日常
  ['on weekends', '週末に', 'I often go shopping on weekends.', '週末によく買い物に行きます。'],
  ['It helps me relax', 'それはリラックスするのに役立つ', 'Listening to music helps me relax.', '音楽を聴くとリラックスできます。'],
  ['spend time with my friends', '友達と過ごす', 'It is fun to spend time with my friends at the park.', '公園で友達と過ごすのは楽しいです。'],
  ['concentrate on ～', '〜に集中する', 'The situation lets us concentrate on studying.', 'その状況は私たちに勉強に集中させます。'],
  // 食べ物
  ['because it is delicious', 'おいしいから', 'I like sushi because it is delicious.', '寿司が好きです。美味しいからです。'],
  ['eat out', '外食する', 'I often eat out with my family on weekends.', '週末によく家族と外食します。'],
  ['try new foods', '新しい食べ物を試す', 'It is fun to try new foods at restaurants.', 'レストランで新しい食べ物を試すのは楽しいです。'],
  ['save time', '時間を節約する', 'Eating out saves time when we are busy.', '忙しいとき、外食は時間を節約できます。'],
  ['eat healthy food', '健康的な食べ物を食べる', 'I want to eat healthy food to stay healthy.', '健康を保つために健康的な食べ物を食べたいです。'],
  // 季節・天気
  ['enjoy outdoor activities', '屋外活動を楽しむ', 'I can enjoy outdoor activities in summer.', '夏には屋外活動を楽しめます。'],
  ['seasonal foods', '旬の食べ物', 'I like to eat seasonal foods in winter.', '冬に旬の食べ物を食べるのが好きです。'],
  ['It is hard to go outside', '外出するのが大変だ', 'It is hard to go outside in winter because it is very cold.', '冬はとても寒いので外出するのが大変です。'],
  // 型（テンプレート）
  ['I have two reasons for feeling this way', 'このように感じる理由は2つあります', 'I have two reasons for feeling this way.', 'このように感じる理由は2つあります。'],
  ['For these reasons', 'これらの理由から', 'For these reasons, I believe that they should try it.', 'これらの理由から、彼らはそれを試すべきだと思います。'],
];

const P2 = [
  // 理由の視点（時間・お金・良い経験）
  ['participate in ～', '〜に参加する', 'Students usually participate in club activities and study hard.', '学生は普通部活に入っており、一生懸命勉強しています。'],
  ['do not have enough time for ～', '〜のための時間がない', 'They do not have enough time for their hobbies.', '彼らには趣味のための時間がありません。'],
  ['cannot afford to ～', '〜する金銭的余裕がない', 'People cannot afford to buy a new car every year.', '人々には毎年新車を買う金銭的余裕はありません。'],
  ['It will be a good chance for ... to ～', '…が〜する良い機会になる', 'It will be a good chance for students to learn about society.', '生徒が社会について学ぶ良い機会になります。'],
  ['see things from different angles', '違った視点から物事を見る', 'The experience allows students to see things from different angles.', 'その経験によって生徒は違った視点から物事を見られるようになります。'],
  ['It will be helpful in the future', 'それは将来役に立つ', 'It will be helpful in the future.', 'それは将来役に立ちます。'],
  // 汎用
  ['allow ～ to do', '〜が…するのを可能にする', 'The app allows us to track our fitness.', 'そのアプリは私たちが健康状態を追跡するのを可能にする。'],
  ['enable ～ to do', '〜が…するのを可能にする', 'The app enables us to track our fitness.', 'そのアプリは私たちが健康状態を追跡するのを可能にする。'],
  ["It's very natural that SV", '〜は当たり前のことだ', "It's very natural that students study hard.", '学生が一生懸命勉強するのは当たり前のことだ。'],
  ['It does not make sense', 'それは理にかなっていない', 'It does not make sense to ban all cars in the city.', '市内のすべての車を禁止するのは理にかなっていない。'],
  ['lead to ～', '〜につながる', 'Eating too much junk food can lead to health problems.', 'ジャンクフードを食べすぎると健康問題につながることがある。'],
  ['so ～ that ...', 'とても〜なので…だ', 'This bag is so light that I can carry it all day.', 'このカバンはとても軽いので、一日中持ち運ぶことができます。'],
  ['be likely to do', '〜する可能性が高い', 'Young people are likely to use smartphones.', '若者はスマホを使う可能性が高い。'],
  ['be unlikely to do', '〜する可能性が低い', 'Older people are unlikely to change their habits quickly.', '年配の人が習慣を素早く変える可能性は低い。'],
  ['have a positive effect on ～', '〜に良い影響を与える', 'The law has a positive effect on society.', 'その法律は社会に良い影響を与えている。'],
  ['have a negative effect on ～', '〜に悪い影響を与える', 'Too much screen time has a negative effect on sleep.', '画面の見すぎは睡眠に悪い影響を与える。'],
  ['rely on ～', '〜に頼る', 'We rely on technology in daily life.', '私たちは日常生活でテクノロジーに頼っている。'],
  ['tend to do', '〜する傾向がある', 'People tend to prefer convenience.', '人々は便利さを好む傾向がある。'],
  ['be inclined to do', '〜する傾向がある', 'Students are inclined to put off difficult tasks.', '生徒は難しい課題を先延ばしにする傾向がある。'],
  ['be required to do', '〜することを求められる', 'Students are required to wear uniforms.', '生徒たちは制服を着ることを求められている。'],
  ['have difficulty ～ing', '〜するのに苦労する', 'Many seniors have difficulty using smartphones.', '多くの高齢者はスマホの使用に苦労している。'],
  ['have a hard time ～ing', '〜するのに苦労する', 'I had a hard time finding the right words.', '適切な言葉を見つけるのに苦労した。'],
  ['struggle to do', '〜するのに苦労する', 'Some students struggle to keep up with the class.', '授業についていくのに苦労する生徒もいる。'],
  ['prevent ～ from ...ing', '〜が…するのを妨げる', 'Bad weather prevented us from going out.', '悪天候で外出できなかった。'],
  ['keep ～ from ...ing', '〜が…するのを妨げる', 'Noise keeps me from concentrating.', '騒音のせいで集中できない。'],
  ['be bound to do', '〜する義務がある', 'We are bound to follow the rules.', '私たちはルールに従う義務がある。'],
  ['have an obligation to do', '〜する義務がある', 'Companies have an obligation to protect their workers.', '企業には労働者を守る義務がある。'],
  ['It is usually difficult for ～ to ...', '〜が…するのはたいてい難しい', 'It is usually difficult for me to wake up early.', '早起きするのは私にとってたいてい難しい。'],
  ['By ～ing, people can ...', '〜することで人々は…できる', 'By studying every day, people can improve their skills.', '毎日勉強することで、人々はスキルを向上させることができる。'],
  ['make ～ easier', '〜を簡単にする', 'Technology makes our lives easier.', 'テクノロジーは私たちの生活を楽にする。'],
  ['make ～ harder', '〜を難しくする', 'Noise makes studying harder.', '騒音は勉強を難しくする。'],
  ['help ～ (to) do', '〜が…するのを助ける', 'Exercise helps us to stay healthy.', '運動は私たちが健康でいるのを助ける。'],
  ['be popular among ～', '〜の間で人気がある', 'This app is popular among young people.', 'このアプリは若者の間で人気がある。'],
  // 形容詞
  ['beneficial', '有益な', 'It is beneficial to take part in team activities.', 'チーム活動に参加することは有益です。'],
  ['essential', '不可欠な', 'It is essential that you get enough sleep before an important test.', '重要なテストの前には十分な睡眠をとることが不可欠です。'],
  ['reliable', '信頼できる', 'It is reliable to use online reviews before making a purchase decision.', '購入の決定をする前にオンラインレビューを使うのは信頼できます。'],
  ['valuable', '価値のある', 'It is valuable to learn from your mistakes to improve yourself.', '自分の失敗から学ぶことは価値があります。'],
  ['reasonable', '妥当な', 'It is reasonable to expect good results after studying hard.', '一生懸命勉強した後に良い結果を期待することは妥当です。'],
  ['practical', '実用的な', 'It is practical to carry a map when you are traveling in an unfamiliar area.', '知らない場所を旅行するときに地図を持っているのは実用的です。'],
  ['affordable', '手頃な価格の', 'It is affordable to buy a quality smartphone these days.', '最近では質の良いスマートフォンを手頃な価格で買うことができます。'],
  ['efficient', '効率的な', 'It is efficient to use a calendar to organize your schedule.', 'スケジュールを整理するためにカレンダーを使うことは効率的です。'],
  ['flexible', '柔軟な', 'It is flexible to work from home when you have a busy schedule.', '忙しい時期には自宅で働くことは柔軟です。'],
  ['generous', '寛大な', 'It is generous to donate to charity and help those in need.', '慈善団体に寄付し、困っている人々を助けることは寛大です。'],
  ['challenging', '挑戦的な、骨の折れる', 'It is challenging to learn a new skill, but it is rewarding.', '新しいスキルを学ぶのは挑戦的ですが、やりがいがあります。'],
  ['innovative', '革新的な', 'It is innovative to use new technology in solving complex problems.', '複雑な問題を解決するために新しい技術を使うことは革新的です。'],
  ['attractive', '魅力的な', 'It is attractive to present your ideas clearly in front of an audience.', '観客の前で自分のアイデアを明確に示すことは魅力的です。'],
  ['troublesome', '面倒な、厄介な', 'Getting up early is sometimes troublesome for students.', '早起きは生徒にとって時々面倒です。'],
  // テーマ別（日常・学校・将来）
  ['spend time doing', '〜して時間を過ごす', 'I spend time reading books every night.', '私は毎晩、本を読んで時間を過ごします。'],
  ['be important for ～', '〜にとって大切である', 'Exercise is important for our health.', '運動は私たちの健康にとって大切です。'],
  ['feel relaxed', 'リラックスする', 'Listening to music makes me feel relaxed.', '音楽を聴くとリラックスします。'],
  ['be convenient for ～', '〜にとって便利だ', 'This app is convenient for shopping.', 'このアプリは買い物に便利です。'],
  ['reduce stress', 'ストレスを減らす', 'Walking outside helps reduce stress.', '外を歩くことはストレスを減らすのに役立ちます。'],
  ['improve health', '健康を向上させる', 'Eating vegetables can improve your health.', '野菜を食べることは健康を向上させることができます。'],
  ['join school events', '学校行事に参加する', 'I joined many school events last year.', '昨年、たくさんの学校行事に参加しました。'],
  ['learn important skills', '大切なスキルを学ぶ', 'At school, we learn important skills for the future.', '学校では将来に向けて大切なスキルを学びます。'],
  ['make friends', '友達を作る', 'I made a lot of friends at school.', '学校でたくさん友達を作りました。'],
  ['work as a team', 'チームで協力する', 'We work as a team during club activities.', '部活動でチームとして協力します。'],
  ['balance study and play', '勉強と遊びのバランスを取る', 'It is important to balance study and play.', '勉強と遊びのバランスを取ることが大切です。'],
  ['have good relationships with ～', '〜と良い関係を築く', 'It is important to have good relationships with teachers.', '先生と良い関係を築くことは大切です。'],
  ['develop communication skills', 'コミュニケーション能力を伸ばす', 'We can develop communication skills at school.', '学校でコミュニケーション能力を伸ばすことができます。'],
  ['get good grades', '良い成績を取る', 'If you study hard, you can get good grades.', '一生懸命勉強すれば、良い成績を取ることができます。'],
  ['have a clear goal', 'はっきりした目標を持つ', 'It is important to have a clear goal for the future.', '将来に向けてはっきりした目標を持つことが大切です。'],
  ['work hard to achieve dreams', '夢をかなえるために努力する', 'I work hard to achieve my dream.', '私は夢をかなえるために努力しています。'],
  ['choose a good career', '良いキャリアを選ぶ', 'I want to choose a good career that suits me.', '自分に合った良いキャリアを選びたいです。'],
  ['improve skills', 'スキルを向上させる', 'We should improve our skills for the future.', '将来のためにスキルを向上させるべきです。'],
  ['be independent', '自立する', 'It is important to be independent after graduation.', '卒業後は自立することが大切です。'],
  ['continue learning', '学び続ける', 'We need to continue learning even after finishing school.', '学校を卒業した後も学び続ける必要があります。'],
  ['save money for the future', '将来のためにお金を貯める', 'I am saving money for my future plans.', '将来の計画のためにお金を貯めています。'],
  ['think about work-life balance', '仕事と生活のバランスを考える', 'It is important to think about work-life balance.', '仕事と生活のバランスを考えることが大切です。'],
  ['gain experience', '経験を積む', 'I want to gain experience by working part-time.', 'アルバイトをして経験を積みたいです。'],
  ['help society', '社会に貢献する', 'I want to help society through my job.', '自分の仕事を通して社会に貢献したいです。'],
];

const G2 = [
  // 汎用
  ['If it were not for ～', 'もし〜がなかったら', 'If it were not for smartphones, it would be inconvenient.', 'もしスマホがなかったら、不便だろう。'],
  ['It is a reasonable way to ～', 'それは〜するのに理にかなった方法だ', 'It is a reasonable way to save money by cooking at home.', '家で料理をするのはお金を節約するのに理にかなった方法です。'],
  ['expect ～ to do', '〜が…することを期待できる', 'We can expect students to study harder with good teachers.', '良い先生がいれば、生徒たちがもっと一生懸命勉強することを期待できます。'],
  ['in terms of ～', '〜の点で、〜に関して', 'In terms of education, Japan has a very high standard.', '教育の点では、日本は非常に高い基準を持っている。'],
  ['the 比較級 SV, the 比較級 SV', '〜すればするほど、ますます…', 'The more people recycle, the cleaner the environment becomes.', '人々がリサイクルすればするほど、環境はますますきれいになる。'],
  ['play a key role in ～', '〜で重要な役割を果たす', 'Education plays a key role in success.', '教育は成功に重要な役割を果たしている。'],
  ['be beneficial to ～', '〜に有益である', 'Exercise is beneficial to both body and mind.', '運動は心と体の両方に有益である。'],
  ['pose a threat to ～', '〜を脅かす', 'Climate change poses a threat to all life.', '気候変動はすべての生命への脅威となっている。'],
  ['have the right to do', '〜する権利がある', 'Everyone has the right to express their opinion.', '誰もが意見を表明する権利を持っている。'],
  // 環境
  ['emit CO2', '二酸化炭素を排出する', 'Factories emit large amounts of CO2.', '工場は大量の二酸化炭素を排出する。'],
  ['greenhouse gases', '温室効果ガス', 'Greenhouse gases are the main cause of global warming.', '温室効果ガスは地球温暖化の主な原因である。'],
  ['protect the environment', '環境を保護する', 'We must protect our natural resources.', '私たちは自然資源を保護しなければならない。'],
  ['take eco-friendly actions', '環境に優しい行動を取る', 'Many people are starting to take eco-friendly actions.', '多くの人が環境に優しい行動を取り始めている。'],
  ['suffer from natural disasters', '自然災害に苦しむ', 'More people suffer from floods every year.', '毎年洪水に苦しむ人が増えている。'],
  ['run out of natural resources', '天然資源が枯渇する', 'We may run out of fossil fuels soon.', '化石燃料は近いうちに枯渇するかもしれない。'],
  ['reduce carbon emissions', '二酸化炭素排出を減らす', 'Using public transport can reduce carbon emissions.', '公共交通の利用は二酸化炭素の排出を減らすことができる。'],
  ['cause environmental damage', '環境破壊を引き起こす', 'Factories cause serious environmental damage.', '工場は深刻な環境破壊を引き起こしている。'],
  ['switch to renewable energy', '再生可能エネルギーに切り替える', 'Many countries are trying to switch to renewable energy.', '多くの国が再生可能エネルギーへの転換を試みている。'],
  ['combat climate change', '気候変動と闘う', 'We need global cooperation to combat climate change.', '気候変動と闘うには世界的な協力が必要だ。'],
  ['preserve biodiversity', '生物多様性を保つ', 'Preserving biodiversity is essential for a healthy ecosystem.', '生物多様性を守ることは健全な生態系に不可欠である。'],
  ['promote sustainability', '持続可能性を促進する', 'We must promote sustainability in all aspects of society.', '私たちは社会のすべての側面で持続可能性を促進しなければならない。'],
  ['minimize waste', '廃棄物を最小限に抑える', 'Households should try to minimize waste by recycling.', '家庭はリサイクルを通じて廃棄物を最小限に抑えるべきだ。'],
  ['address climate change', '気候変動に対処する', 'We must all work together to address climate change.', '私たちは気候変動に対処するために共に働かなければならない。'],
  ['support renewable energy', '再生可能エネルギーを支持する', 'Countries need to support renewable energy.', '各国は再生可能エネルギーを支持する必要がある。'],
  ['increase environmental awareness', '環境意識を高める', 'Environmental campaigns can help increase environmental awareness.', '環境キャンペーンは環境意識を高めるのに役立つ。'],
  // 教育
  ['play an important role in ～', '〜で重要な役割を果たす', 'Teachers play an important role in education.', '教師は教育において重要な役割を果たしている。'],
  ['have access to ～', '〜を利用する機会がある', 'All children should have access to education.', 'すべての子どもが教育を受ける機会を持つべきだ。'],
  ['be essential for future success', '将来の成功に不可欠である', 'Basic education is essential for future success.', '基礎教育は将来の成功に不可欠だ。'],
  ['develop critical thinking skills', '批判的思考力を育てる', 'Good teachers help students develop critical thinking skills.', '良い教師は生徒が批判的思考力を育てるのを助ける。'],
  ['improve academic performance', '学業成績を向上させる', "Proper sleep can improve students' academic performance.", '十分な睡眠は生徒の学業成績を向上させる。'],
  // 技術
  ['develop technology', '技術を開発する', 'We need to develop new technology to solve social problems.', '社会問題を解決するために新しい技術を開発する必要がある。'],
  ['be useful in daily life', '日常生活で役立つ', 'Technology is useful in many areas of our daily life.', 'テクノロジーは私たちの日常生活の多くの分野で役立っている。'],
  ['become more common', 'より一般的になる', 'Online interviews may become more common in the future.', 'オンライン面接は将来より一般的になるかもしれない。'],
  ['save time and effort', '時間と労力を節約する', 'Technology can help us save time and effort at work.', 'テクノロジーは仕事の時間と労力を節約してくれる。'],
  ['solve social problems', '社会問題を解決する', 'New inventions can help solve environmental problems.', '新しい発明は環境問題の解決に役立つ可能性がある。'],
  ['make life more convenient', '生活をより便利にする', 'Smartphones have made our lives more convenient.', 'スマートフォンは私たちの生活をより便利にしてくれた。'],
  ['reduce human labor', '人間の労働を減らす', 'Robots can reduce human labor in dangerous jobs.', 'ロボットは危険な仕事で人間の労働を減らすことができる。'],
  ['raise security concerns', '安全面での懸念を引き起こす', 'Using new technology sometimes raises security concerns.', '新しい技術の使用は時に安全上の懸念を引き起こす。'],
  ['be related to privacy', 'プライバシーに関係する', 'Online voting is related to privacy and security issues.', 'オンライン投票はプライバシーやセキュリティの問題に関係している。'],
  ['become a part of our life', '生活の一部になる', 'Technology has become a part of our daily life.', 'テクノロジーは私たちの日常生活の一部になっている。'],
  ['improve our quality of life', '生活の質を向上させる', 'New technologies have improved our quality of life.', '新しいテクノロジーは私たちの生活の質を向上させた。'],
  ['lead to job loss', '失業を引き起こす', 'AI may lead to job loss in some industries.', 'AIは一部の産業で失業を引き起こす可能性がある。'],
  ['create new job opportunities', '新たな雇用機会を生む', 'The IT industry has created many new job opportunities.', 'IT業界は多くの新しい雇用機会を生んできた。'],
  ['become increasingly dependent on ～', '〜にますます依存するようになる', 'We are becoming increasingly dependent on digital tools.', '私たちはデジタルツールにますます依存するようになっている。'],
  ['have both advantages and disadvantages', '長所と短所の両方がある', 'Technology has both advantages and disadvantages.', 'テクノロジーには長所と短所の両方がある。'],
  // 社会
  ['face social problems', '社会問題に直面する', 'Many countries face serious social problems.', '多くの国が深刻な社会問題に直面している。'],
  ['deal with social issues', '社会問題に取り組む', 'We should work together to solve social issues.', '私たちは協力して社会問題に取り組むべきだ。'],
  ['improve society', '社会を改善する', 'Education is important to improve society.', '教育は社会を改善するために重要である。'],
  ['support people in need', '困っている人々を支援する', 'Many people do volunteer work to support people in need.', '多くの人が困っている人々を支援するためにボランティア活動をしている。'],
  ['promote equality', '平等を促進する', 'We must promote equality in the workplace.', '職場での平等を促進するべきだ。'],
  ['raise awareness of ～', '〜への意識を高める', 'The media can raise awareness of social issues.', 'メディアは社会問題への意識を高めることができる。'],
  ['create a better society', 'より良い社会を作る', 'Young people can help create a better society.', '若者はより良い社会を作る手助けができる。'],
  ['respect different values', '異なる価値観を尊重する', 'It is important to respect different values in society.', '社会では異なる価値観を尊重することが重要だ。'],
  ['have a strong sense of community', '強い地域社会意識を持つ', 'In small towns, people often have a strong sense of community.', '小さな町では、地域社会意識が強いことが多い。'],
  ['face population problems', '人口問題に直面する', 'Japan is facing population problems such as aging.', '日本は高齢化などの人口問題に直面している。'],
  ['use social media wisely', 'SNSを賢く使う', 'Young people should learn to use social media wisely.', '若者はSNSを賢く使うことを学ぶべきだ。'],
  ['have equal opportunities', '平等な機会を持つ', 'All people should have equal opportunities.', 'すべての人が平等な機会を持つべきである。'],
  ['support the disadvantaged', '弱い立場の人々を支援する', 'Governments should support the disadvantaged.', '政府は弱い立場の人々を支援すべきである。'],
  ['raise public awareness', '人々の意識を高める', 'We need to raise public awareness about discrimination.', '差別について人々の意識を高める必要がある。'],
  ['be influenced by social media', 'SNSに影響される', 'Teenagers are often influenced by social media.', 'ティーンエイジャーはしばしばSNSに影響される。'],
  ['encourage community engagement', '地域社会への関わりを促す', 'The event encourages community engagement.', 'そのイベントは地域社会への関わりを促している。'],
  ['promote gender equality', '男女平等を促進する', 'We should promote gender equality at workplaces.', '職場での男女平等を促進すべきである。'],
  ['suffer from loneliness', '孤独に苦しむ', 'Many elderly people suffer from loneliness.', '多くの高齢者が孤独に苦しんでいる。'],
  // 経済
  ['boost the economy', '経済を活性化させる', 'Tourism can help boost the economy.', '観光は経済を活性化させる助けになる。'],
  ['create new jobs', '新しい雇用を生み出す', 'New industries create new jobs.', '新しい産業は新しい雇用を生み出す。'],
  ['increase income', '収入を増やす', 'Many people want to increase their income.', '多くの人が収入を増やしたいと考えている。'],
  ['support local businesses', '地元の企業を支援する', 'Buying local products supports local businesses.', '地元の製品を買うことは地元の企業を支援することになる。'],
  ['reduce economic gaps', '経済格差を減らす', 'We need to reduce the economic gap between rich and poor.', '私たちは貧富の経済格差を減らす必要がある。'],
  ['increase consumer spending', '消費者の支出を増やす', 'Sales and discounts can increase consumer spending.', 'セールや割引は消費者の支出を増やす可能性がある。'],
  ['stimulate economic growth', '経済成長を促進する', 'New technology can stimulate economic growth.', '新しい技術は経済成長を促進する可能性がある。'],
  ['face economic challenges', '経済的な課題に直面する', 'The country is facing many economic challenges.', 'その国は多くの経済的な課題に直面している。'],
  ['improve working conditions', '労働環境を改善する', 'Better working conditions lead to higher productivity.', 'より良い労働環境は生産性の向上につながる。'],
  ['attract foreign investment', '海外からの投資を呼び込む', 'The government is trying to attract foreign investment.', '政府は外国からの投資を呼び込もうとしている。'],
  ['increase the cost of living', '生活費が上がる', 'In big cities, the cost of living is increasing.', '大都市では生活費が上がっている。'],
  ['face financial difficulties', '経済的な困難に直面する', 'Many families are facing financial difficulties.', '多くの家庭が経済的困難に直面している。'],
  ['income gap', '所得格差', 'The income gap is becoming a serious issue.', '所得格差は深刻な問題になりつつある。'],
  ['raise the consumption tax', '消費税を上げる', 'The government decided to raise the consumption tax.', '政府は消費税を上げることを決定した。'],
  ['support small and medium-sized businesses', '中小企業を支援する', 'The government should support small and medium-sized businesses.', '政府は中小企業を支援すべきである。'],
  // 文化
  ['understand cultural differences', '文化の違いを理解する', 'We should try to understand cultural differences.', '私たちは文化の違いを理解する努力をすべきだ。'],
  ['respect other cultures', '他の文化を尊重する', 'We need to respect other cultures when we travel.', '旅行する時は他の文化を尊重する必要がある。'],
  ['experience a new culture', '新しい文化を体験する', 'Studying abroad is a good way to experience a new culture.', '留学は新しい文化を体験する良い方法だ。'],
  ['preserve traditional culture', '伝統文化を守る', 'We should preserve traditional culture for future generations.', '私たちは伝統文化を未来の世代のために守るべきだ。'],
  ['lose cultural identity', '文化的アイデンティティを失う', 'Globalization may cause people to lose their cultural identity.', 'グローバル化は人々が文化的アイデンティティを失う原因になるかもしれない。'],
  ['promote cultural exchange', '文化交流を促進する', 'Cultural events help promote cultural exchange.', '文化的なイベントは文化交流を促進する助けになる。'],
  ['cultural diversity', '文化的多様性', 'Cultural diversity makes our society more interesting.', '文化的多様性は私たちの社会をより面白くする。'],
  ['value cultural heritage', '文化遺産を大切にする', 'We should value our cultural heritage.', '私たちは自分たちの文化遺産を大切にすべきである。'],
  ['be influenced by Western culture', '西洋文化の影響を受ける', 'Japanese fashion has been influenced by Western culture.', '日本のファッションは西洋文化の影響を受けてきた。'],
  // 健康
  ['stay healthy', '健康を保つ', 'It is important to stay healthy by eating well and exercising.', 'よく食べて運動することで健康を保つことは大切だ。'],
  ['have a balanced diet', 'バランスの取れた食事をする', 'Children should have a balanced diet to grow well.', '子どもたちは健やかに成長するためにバランスの取れた食事をとるべきだ。'],
  ['get regular exercise', '定期的に運動する', 'Getting regular exercise helps prevent illness.', '定期的な運動は病気の予防に役立つ。'],
  ['suffer from lifestyle diseases', '生活習慣病にかかる', 'More people suffer from lifestyle diseases these days.', '最近、生活習慣病にかかる人が増えている。'],
  ['prevent illness', '病気を予防する', 'Washing your hands often can prevent illness.', '手をよく洗うことで病気を予防できる。'],
  ['maintain mental health', 'メンタルヘルスを維持する', 'Spending time with friends helps maintain mental health.', '友人と過ごすことはメンタルヘルスの維持に役立つ。'],
  ['improve public health', '公衆衛生を向上させる', 'Vaccinations can improve public health.', 'ワクチン接種は公衆衛生の向上に役立つ。'],
  ['lead a healthy lifestyle', '健康的な生活を送る', 'More people want to lead a healthy lifestyle.', 'より多くの人が健康的な生活を送りたいと考えている。'],
  ['avoid unhealthy habits', '不健康な習慣を避ける', 'We should avoid unhealthy habits like smoking.', '喫煙のような不健康な習慣は避けるべきだ。'],
  ['access medical services', '医療サービスを受ける', 'It is difficult for some people to access medical services.', '医療サービスを受けるのが難しい人もいる。'],
];

/** つなぎ言葉。3冊とも同じ一覧が載っている。 */
const MARKERS = [
  ['Although ～', '〜だけれども', 'Although it was raining, we went out.', '雨が降っていたけれども、私たちは出かけた。'],
  ['Even though ～', '〜にもかかわらず', 'Even though it was difficult, he did not give up.', '難しかったにもかかわらず、彼はあきらめなかった。'],
  ['Admittedly, ～', '確かに〜だけど', 'Admittedly, the cost is high, but the benefit is greater.', '確かに費用は高いが、利益のほうが大きい。'],
  ['It is true that ～, but ...', '確かに〜だが、…', 'It is true that it costs money, but it saves time.', '確かにお金はかかるが、時間を節約できる。'],
  ['For instance, ～', 'たとえば', 'For instance, many students use online tools.', 'たとえば、多くの生徒がオンラインツールを使っている。'],
  ['To give an example, ～', '例を挙げると', 'To give an example, some cities have free buses.', '例を挙げると、無料のバスがある都市もある。'],
  ['In addition, ～', 'さらに', 'In addition, it is good for the environment.', 'さらに、それは環境に良い。'],
  ['Moreover, ～', 'その上', 'Moreover, it does not cost much money.', 'その上、あまりお金がかからない。'],
  ['Besides, ～', 'それに', 'Besides, it is easy to start.', 'それに、始めるのが簡単だ。'],
  ['In contrast, ～', '対照的に', 'In contrast, big cities have many choices.', '対照的に、大都市には多くの選択肢がある。'],
  ['This is because ～', 'これは〜が理由である', 'This is because young people have moved to cities.', 'これは若者が都市へ移ったからである。'],
  ['As a result, ～', 'その結果', 'As a result, the number of students decreased.', 'その結果、生徒の数が減った。'],
  ['Consequently, ～', '結果として', 'Consequently, the shop had to close.', '結果として、その店は閉じなければならなかった。'],
  ['Thus, ～', 'したがって', 'Thus, we should think about another way.', 'したがって、別の方法を考えるべきだ。'],
  ['In conclusion, ～', '結論として', 'In conclusion, I believe that schools should change.', '結論として、学校は変わるべきだと思う。'],
  ['To sum up, ～', '要約すると', 'To sum up, the benefits are greater than the costs.', '要約すると、利益は費用より大きい。'],
  ['In summary, ～', 'まとめると', 'In summary, both sides have good points.', 'まとめると、どちらの側にも良い点がある。'],
  ['Overall, ～', '全体として', 'Overall, the change was a good one.', '全体として、その変化は良いものだった。'],
];

module.exports = {
  /** 級ごとのフレーズ。やさしい順に見て、先に出たものを採る。 */
  BY_GRADE: [
    { grade: 3, level: 3, entries: G3 },
    { grade: 'pre2', level: 4, entries: P2 },
    { grade: 2, level: 5, entries: G2 },
    // つなぎ言葉は3級から使うので3級に置く
    { grade: 3, level: 3, entries: MARKERS },
  ],
};
